# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f15314bc083a4525353bcad9ec7b2b9341f511b3a4ec7a0750b90f5697041f530ec06b2dd811606cbd51341fb2f6aace61599b0496280ef769662ae7a2f48c1

test:
  secret_key_base: 2ce598e1f0551c2e446dc7c0ae1415618a8653b50371fb3ec1459f7a660e6dffff3e0450e89ec8ee48fca5b5c45710d60cdd28edb74f13c9306e52635f82834c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
